export default {
  view: {
    iosDynamicNavbar: false,
  },
  navbar: {},
  autocomplete: {
    popupCloseLinkText: '关闭',
    pageBackLinkText: '返回',
    // pageTitle: this.$t('app_name'),
    searchbarPlaceholder: '搜索...',
    searchbarDisableText: '取消',
    notFoundText: '未找到匹配项',
  },
  calendar: {
    monthNames: [
      '1月',
      '2月',
      '3月',
      '4月',
      '5月',
      '6月',
      '7月',
      '8月',
      '9月',
      '10月',
      '11月',
      '12月',
    ],
    monthNamesShort: [
      '1月',
      '2月',
      '3月',
      '4月',
      '5月',
      '6月',
      '7月',
      '8月',
      '9月',
      '10月',
      '11月',
      '12月',
    ],
    dayNames: [
      '星期一',
      '星期二',
      '星期三',
      '星期四',
      '星期五',
      '星期六',
      '星期日',
    ],
    dayNamesShort: ['周一', '周二', '周三', '周四', '周五', '周六', '周日'],
  },
  dialog: {
    // title: this.$t('app_name'),
    buttonOk: '确定',
    buttonCancel: '取消',
    preloaderTitle: '加载中...',
    progressTitle: '加载中...',
  },
  smartSelect: {
    pageTitle: '请选择',
    pageBackLinkText: '返回',
    popupCloseLinkText: '关闭',
    sheetCloseLinkText: '完成',
    searchbarPlaceholder: '搜索',
    searchbarDisableText: '取消',
  },
};
